import {
  BOTTOMSHEET_HANDLE_HEIGHT,
  BOTTOM_TAB_BAR_HEIGHT,
  DAY_CELL_HEIGHT,
  PARTY_CARD_HEIGHT,
  WINDOW_HEIGHT,
  WINDOW_WIDTH,
} from '@/shared/constants/layout';
import { DEPARTMENT_OPTIONS } from '@/shared/constants/departments';
export {
  DEPARTURE_LOCATION,
  DEPARTURE_OPTIONS,
  DESTINATION_LOCATION,
  DESTINATION_OPTIONS,
} from '@/features/taxi/model/constants';

export {
  BOTTOMSHEET_HANDLE_HEIGHT,
  BOTTOM_TAB_BAR_HEIGHT,
  DAY_CELL_HEIGHT,
  DEPARTMENT_OPTIONS,
  PARTY_CARD_HEIGHT,
  WINDOW_HEIGHT,
  WINDOW_WIDTH,
};
