export const dummyParties = [
    {
      id: '1',
      departureTime: '오전 08:50',
      departure: '가천대 정문',
      destination: 'ai 공학관',
      members: 3,
      maxMembers: 4,
      tags: ['#아침', '#등교', '#빠른출발'],
      location: { latitude: 37.4501, longitude: 127.1287 },
    },
    {
      id: '2',
      departureTime: '오후 01:30',
      departure: '성결대 정문',
      destination: '기숙사',
      members: 2,
      maxMembers: 4,
      tags: ['#점심', '#기숙사', '#여유'],
      location: { latitude: 37.3921, longitude: 126.9487 },
    },
    {
      id: '3',
      departureTime: '오후 06:10',
      departure: '정왕역',
      destination: '가천대',
      members: 4,
      maxMembers: 4,
      tags: ['#퇴근', '#만차', '#정시출발'],
      location: { latitude: 37.3614, longitude: 126.9357 },
    },
    {
      id: '4',
      departureTime: '오전 09:00',
      departure: '수원역',
      destination: '수원시청',
      members: 1,
      maxMembers: 3,
      tags: ['#아침', '#출근', '#빠른출발'],
      location: { latitude: 37.2659, longitude: 127.0004 },
    },
    {
      id: '5',
      departureTime: '오후 02:00',
      departure: '인천대입구역',
      destination: '인천대학교',
      members: 2,
      maxMembers: 4,
      tags: ['#등교', '#여유', '#학생'],
      location: { latitude: 37.3861, longitude: 126.6399 },
    },
    {
      id: '6',
      departureTime: '오후 05:30',
      departure: '강남역',
      destination: '서울역',
      members: 3,
      maxMembers: 4,
      tags: ['#퇴근', '#빠른출발', '#정시출발'],
      location: { latitude: 37.4981, longitude: 127.0276 },
    },
    {
      id: '7',
      departureTime: '오전 10:00',
      departure: '부천역',
      destination: '부천시청',
      members: 1,
      maxMembers: 3,
      tags: ['#아침', '#출근', '#여유'],
      location: { latitude: 37.4854, longitude: 126.7827 },
    },
    {
      id: '8',
      departureTime: '오후 03:00',
      departure: '일산역',
      destination: '일산동구청',
      members: 2,
      maxMembers: 4,
      tags: ['#등교', '#여유', '#학생'],
      location: { latitude: 37.6821, longitude: 126.7698 },
    },
    {
      id: '9',
      departureTime: '오후 07:00',
      departure: '분당역',
      destination: '분당구청',
      members: 3,
      maxMembers: 4,
      tags: ['#퇴근', '#빠른출발', '#정시출발'],
      location: { latitude: 37.3519, longitude: 127.1087 },
    }
  ];