import { Party } from "../../types/party";

export const dummyParties: Party[] = [
    {
      id: '1',
      departureTime: '오전 08:50',
      departure: '명학역',
      destination: '성결대학교',
      members: 3,
      maxMembers: 4,
      leader: '홍길동',
      tags: ['#아침아침아', '#등교등교등', '#빠른출발발' ],
      location: {latitude: 37.3846167, longitude: 126.935323965},
      description: '명학역 1번출구 앞 뿔테안경입니다',
    },
    {
      id: '2',
      departureTime: '오후 01:30',
      departure: '성결대학교',
      destination: '명학역',
      members: 2,
      maxMembers: 4,
      leader: '김길동',
      tags: ['#점심', '#기숙사', '#여유'],
      location: {latitude: 37.38131, longitude: 126.9288},
      description: '8:45분까지 빨리 모이기!',
    },
    {
      id: '3',
      departureTime: '오후 06:10',
      departure: '범계역',
      destination: '성결대학교',
      members: 4,
      maxMembers: 4,
      leader: '이길동',
      tags: ['#퇴근', '#만차', '#정시출발'],
      location: {latitude: 37.3896500, longitude: 126.9506139},
      description: '범계역에서 성결대학교로 이동하는 택시 파티입니다!',
    },
    {
      id: '4',
      departureTime: '오전 09:00',
      departure: '안양역',
      destination: '성결대학교',
      members: 1,
      maxMembers: 3,
      leader: '박길동',
      tags: ['#아침', '#출근', '#빠른출발'],
      location: {latitude: 37.4016640, longitude: 126.92271684},
      description: '안양역에서 성결대학교로 이동하는 택시 파티입니다!',
    },
    {
      id: '5',
      departureTime: '오후 02:00',
      departure: '금정역',
      destination: '성결대학교',
      members: 2,
      maxMembers: 4,
      leader: '최길동',
      tags: ['#등교', '#여유', '#학생'],
      location: {latitude: 37.371838475, longitude: 126.943650313},
      description: '빨리빨리 오세요!!!',
    },
    {
      id: '6',
      departureTime: '오후 05:30',
      departure: '성결대학교',
      destination: '금정역',
      members: 3,
      maxMembers: 4,
      leader: '정길동',
      tags: ['#퇴근', '#빠른출발', '#정시출발'],
      location: {latitude: 37.38131, longitude: 126.9288},
      description: '강남역에서 서울역으로 이동하는 택시 파티입니다!',
    },
    {
      id: '7',
      departureTime: '오전 10:00',
      departure: '부천역',
      destination: '부천시청',
      members: 1,
      maxMembers: 3,
      leader: '오길동',
      tags: ['#아침', '#출근', '#여유'],
      location: { latitude: 37.4854, longitude: 126.7827 },
      description: '부천역에서 부천시청으로 이동하는 택시 파티입니다!',
    },
    {
      id: '8',
      departureTime: '오후 03:00',
      departure: '일산역',
      destination: '일산동구청',
      members: 2,
      maxMembers: 4,
      leader: '유길동',
      tags: ['#등교', '#여유', '#학생'],
      location: { latitude: 37.6821, longitude: 126.7698 },
      description: '일산역에서 일산동구청으로 이동하는 택시 파티입니다!',
    },
    // {
    //   id: '9',
    //   departureTime: '오후 07:00',
    //   departure: '분당역',
    //   destination: '분당구청',
    //   members: 3,
    //   maxMembers: 4,
    //   leader: '장길동',
    //   tags: ['#퇴근', '#빠른출발', '#정시출발'],
    //   location: { latitude: 37.3519, longitude: 127.1087 },
    //   description: '분당역에서 분당구청으로 이동하는 택시 파티입니다!',
    // },
  ];