export {
  useBoardActions,
  useBoardBookmarks,
  useBoardCategoryCounts,
  useBoardComments,
  useBoardEdit,
  useBoardLikes,
  useBoardPost,
  useBoardPosts,
  useBoardWrite,
  usePostActions,
  useUserBoardInteractions,
} from '@/features/board';
export type {
  UseBoardActionsResult,
  UseBoardBookmarksResult,
  UseBoardCategoryCountsResult,
  UseBoardCommentsResult,
  UseBoardEditResult,
  UseBoardLikesResult,
  UseBoardPostResult,
  UseBoardPostsResult,
  UseBoardWriteResult,
  UseUserBoardInteractionsResult,
} from '@/features/board';
